### ISSUE TITLE
Drop Babel 

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-cli#51]
I think babel slows down the build process quite a bit. Why not drop babel and use a more up-to-date node version, to use ES6 features natively? 

See feature comparison here: http://node.green/ 

Thoughts? Feedback?

**Comment by gakimball** [comment]
When Foundation 6 shipped, the oldest Node version we supported was 0.12. Whenever Foundation 7 ships, we're likely bumping that to at least 4.x, so that's when we'll shift all of our Node tooling to match.

We're already in the process of shifting some of our tools, such as [Panini](https://github.com/zurb/panini/tree/v2.0-alt), to use newer ECMAScript features supported by Node 4.
